name: cityrunners
description: "The HK MTR based game"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.4
  cupertino_icons: ^1.0.6
  geolocator: ^12.0.0
  http: ^1.2.1
  shared_preferences: ^2.2.3
  web_socket_channel: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
